### ISSUE TITLE
.NET framework version not match with v4.8 but i already installed 4.8 runtime

### ISSUE THREAD

**Issue by ghost** [Franco28/Moto_Boot_Logo_Maker#1]
Hello, i was trying to run the program in the portable version but everytime that i try to open it it says
`.NET framework version does not match with v4.8!
Debug info: 4.7.2`
Al the other apps detect 4.8 fine. I tried reinstalling windows and use the setup version, uninstalling and installing, Cleaning Appdata, I tried to modify Moto_Boot_Logo_Maker.exe.conf to set a lower version and Using a hex editor to edit the Binary.exe

Im currently runing windows 10 ltsb, i tried with ltsc, 7 and wine too

**Comment by ghost** [comment]
i fixed by edit .net framework ver of the exe file with dns spy to another version

**Comment by Franco28** [comment]
Hey! sorry, im not maintaining anymore this tool, and the code is a mess lol 😬
